#!/usr/bin/env bash

cd $HOME/go/src/github.com/nknorg/nkn

git fetch &> /dev/null

LOCAL=$(git rev-parse HEAD)
UPSTREAM=$(git rev-parse @{u})

if [ $LOCAL != $UPSTREAM ]
then
	systemctl stop nkn.service
	git merge
	make deepclean
	make glide
	make vendor
	make
	systemctl start nkn.service
	chown -R "EDITNAME:EDITNAME" "$HOME/go"
	echo "$(date) -- UPDATE FINISHED"
else
	echo "$(date) -- Already up-to-date"
fi
